# Generated by Django 5.1.11 on 2025-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
