# Generated by Django 5.1.11 on 2025-07-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0005_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(),
        ),
    ]
