# Generated by Django 5.1.11 on 2025-07-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="borrowing",
        ),
        migrations.DeleteModel(
            name="Borrowing",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
