# Generated by Django 5.1.11 on 2025-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_payment_borrowing_delete_borrowing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "HARD"), ("SOFT", "SOFT")], max_length=100
            ),
        ),
    ]
